#!/bin/sh

brew cask install adium
brew cask install skype
brew cask install dropbox
brew cask install utorrent
brew cask install the-unarchiver
brew cask install caffeine
brew cask install gfxcardstatus
brew cask install firefox
brew cask install gpgtools
brew cask install iterm2
brew cask install mailmate
brew cask install fontprep
brew cask install flux
brew cask install onyx
brew cask install sourcetree
brew cask install mplayer-osx-extended
brew cask install xamarin-studio
brew cask install xld
brew cask install nvalt
brew cask install torbrowser
brew cask install qlcolorcode
brew cask install qlmarkdown
brew cask install qlstephen
brew cask install qlprettypatch
brew cask install quicklook-csv
brew cask install quicklook-json
brew cask install webp-quicklook
brew cask install suspicious-package
brew cask install betterzipql
brew cask install launchrocket
